name: "Terraform Plan and Apply"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'main/**'
  push:
    branches:
      - main
    paths:
      - 'main/**'
  workflow_dispatch:

env:
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  AWS_REGION: ${{ secrets.BACKEND_REGION }}

jobs:
  terraform:
    if: github.repository == 'batzsalmassi/python-project'
    name: "Terraform Plan and Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CLOUDGURU_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CLOUDGURU_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Terraform
        id: init
        working-directory: ./main
        run: terraform init

      - name: Create backend.tf
        run: |
          cat <<EOF > ./main/backend.tf
          terraform {
            backend "s3" {
              bucket = "${{ secrets.BUCKET_TF_STATE }}"
              key    = "terraform/python-master-project.tfstate"
              region = "${{ env.AWS_REGION }}"
            }
          }
          EOF

      - name: Terraform init with backend
        working-directory: ./main
        run: terraform init

      - name: Terraform format check
        id: fmt-check
        working-directory: ./main
        run: terraform fmt -check
        continue-on-error: true

      - name: Automatically format Terraform code if not formatted
        if: steps.fmt-check.outcome == 'failure'
        working-directory: ./main
        run: terraform fmt

      - name: Commit formatted code
        if: steps.fmt-check.outcome == 'failure' && github.event_name == 'pull_request'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git checkout ${{ github.head_ref }}
          git add .
          git diff --staged --quiet || (git commit -m "Automatically formatted Terraform code" && git push origin ${{ github.head_ref }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform plan
        id: plan
        if: github.event_name == 'pull_request'
        working-directory: ./main
        env:
          SHODAN_API_KEY: ${{ secrets.SHODAN_API_KEY }}
          TF_VAR_personal_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_personal_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform plan -no-color -input=false \
            -var "shodan_api_key=$SHODAN_API_KEY" \
            -var "personal_aws_access_key=$TF_VAR_personal_aws_access_key" \
            -var "personal_aws_secret_key=$TF_VAR_personal_aws_secret_key" \
            -out=tfplan

      - name: Show Terraform Plan
        run: |
          if [ -f ./main/tfplan ]; then
            if ! terraform show -no-color ./main/tfplan > plan_output.txt 2>plan_error.txt; then
              echo "Error occurred while showing plan. Using sanitized plan file contents instead."
              # Use grep to exclude lines containing sensitive information
              grep -vE '(access_key|secret_key|api_key).*= ' ./main/tfplan > plan_output.txt
              echo "Note: Some information has been removed to protect sensitive data." >> plan_output.txt
            fi
            sed 's/\(access_key\|secret_key\|api_key\).*= "[^"]*"/\1 = <redacted>/g' plan_output.txt > redacted_plan.txt
            if grep -qE '(AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY)' redacted_plan.txt; then
              echo "Error: Sensitive information detected in plan output" > redacted_plan.txt
            elif [ ! -s redacted_plan.txt ]; then
              echo "No changes detected in the plan" > redacted_plan.txt
            fi
          else
            echo "No tfplan file found" > redacted_plan.txt
          fi

      - name: Summarize Terraform Plan
        id: plan_summary
        run: |
          if [ -f redacted_plan.txt ]; then
            if grep -q "No changes detected in the plan" redacted_plan.txt; then
              echo "::set-output name=SUMMARY::No changes detected"
            elif grep -q "No tfplan file found" redacted_plan.txt; then
              echo "::set-output name=SUMMARY::Error: No Terraform plan file found"
            else
              RESOURCES_ADDED=$(grep -c '^\s*\+ ' redacted_plan.txt || echo "0")
              RESOURCES_CHANGED=$(grep -c '^\s*~ ' redacted_plan.txt || echo "0")
              RESOURCES_DESTROYED=$(grep -c '^\s*- ' redacted_plan.txt || echo "0")

              # Proper formatting for GitHub outputs
              echo "::set-output name=RESOURCES_ADDED::$RESOURCES_ADDED"
              echo "::set-output name=RESOURCES_CHANGED::$RESOURCES_CHANGED"
              echo "::set-output name=RESOURCES_DESTROYED::$RESOURCES_DESTROYED"
            fi
          else
            echo "::set-output name=SUMMARY::Error: redacted_plan.txt not found"
          fi

      - name: Log Plan Summary
        run: |
          echo "Resources to add: ${{ steps.plan_summary.outputs.RESOURCES_ADDED }}"
          echo "Resources to change: ${{ steps.plan_summary.outputs.RESOURCES_CHANGED }}"
          echo "Resources to destroy: ${{ steps.plan_summary.outputs.RESOURCES_DESTROYED }}"

      - name: Post Plan Summary Comment
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const planOutput = fs.readFileSync('redacted_plan.txt', 'utf8');
            const output = `#### Terraform Plan Summary
            ${{ steps.plan_summary.outputs.SUMMARY }}
            
            <details><summary>Show Redacted Plan</summary>
            
            \`\`\`hcl
            ${planOutput}
            \`\`\`
            </details>
            
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

      - name: Cache Terraform Plan
        uses: actions/cache@v3
        with:
          path: ./main/tfplan
          key: ${{ runner.os }}-terraform-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: ./main
        env:
          SHODAN_API_KEY: ${{ secrets.SHODAN_API_KEY }}
          TF_VAR_personal_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_personal_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          if [ -f tfplan ]; then
            terraform apply -auto-approve -input=false tfplan
          else
            echo "Error: tfplan file not found. Re-running plan."
            terraform plan -no-color -input=false \
              -var "shodan_api_key=$SHODAN_API_KEY" \
              -var "personal_aws_access_key=$TF_VAR_personal_aws_access_key" \
              -var "personal_aws_secret_key=$TF_VAR_personal_aws_secret_key" \
              -out=tfplan
            terraform apply -auto-approve -input=false tfplan
          fi

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
